### ISSUE TITLE
✨FRONT : 마이 페이지에서 새로 고침 시 API가 작동하지 않음

### ISSUE THREAD

**Issue by xiu0327** [xiu0327/2023-refrigerator-recipe#67]
### 이슈 내용
- 마이 페이지에서 새로 고침 시 Authorization 헤더에 토큰이 없음
- 대부분의 API가 새로고침하면 제대로 작동하지 않음
- 처음 로그인을 했을 때
<img width="400" alt="스크린샷 2023-05-21 오후 11 34 41" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/f0ec8f63-b128-4cda-8a42-9f24e5f387ca">
<br>
<br>
- 마이페이지에서 새로 고침을 했을 때
<br>
<br>
<img width="400" alt="스크린샷 2023-05-21 오후 11 35 38" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/e16579ff-fc9a-4fe6-9033-f58a5c1212b2">

### 실행 환경
- front-main-v1 브랜치 clone
- node version v18.0.0으로 조정
- yarn install을 통해 node_modules 생성
- yarn dev 실행

**Comment by j-kyung99** [comment]
추후 로그인 코드 변경 예정

**Comment by mxxseonkim** [comment]
### 수정 내용
- 페이지 새로고침 시 instance(axios 객체)가 초기화되어 instance의 Authorization 헤더에 저장된 accessToken이 사라짐 → 401 Unauthorized 오류 발생
- Unauthorized 오류 발생시 accessToken 재발행하도록 구현
- 냉장고, 레시피, 마이페이지에서 테스트 완료
- 후에 redux 등을 활용해 보완 필요
