### ISSUE TITLE
✨FRONT : 레시피 목록 조회 시 undefined alert 창 연속 발생

### ISSUE THREAD

**Issue by xiu0327** [xiu0327/2023-refrigerator-recipe#69]
### 이슈 상황
<img width="513" alt="스크린샷 2023-05-22 오전 12 22 48" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/a0bf6ba2-24d5-4d6a-871f-fb3daf7885de">
<br>
- 레시피 목록 조회 페이지로 넘어가면 위와 같은 팝업창이 계속 발생

**Comment by xiu0327** [comment]
나의 북마크 조회 페이지 (http://localhost:3000/bookmark) 에서도 동일한 오류 발생

**Comment by j-kyung99** [comment]
로그인이 유지가 안되는 상황으로 로그인을 해야 볼 수 있는 화면에서는 로그인 정보를 읽어오지 못하여 현상 발생중. 추후 로그인 관련 코드 변경 예정임.

**Comment by mxxseonkim** [comment]
이 오류가 나는 원인은, merge 전에 내가 레시피 목록에서 로그인을 임의로 호출 했기 때문
(냉장고, 레시피 부분 구현이라 임의로 로그인을 해야지 API를 정상적으로 호출할 수 있었음)
