### ISSUE TITLE
✨FRONT : 로그인 창에서 아이디와 비밀번호를 입력하고 엔터를 치면 이동하도록 수정 요청

### ISSUE THREAD

**Issue by xiu0327** [xiu0327/2023-refrigerator-recipe#70]
## 이슈 상황
- 로그인 페이지에서 아이디/비밀번호를 입력하고 버튼을 눌러야 다음 페이지로 이동 가능

## 요청 사항
- 모바일 웹: 엔터(확인) 버튼을 누르면 다음 페이지로 이동하도록
- 웹: 엔터를 누르면 바로 다음 페이지로 이동하도록

**Comment by j-kyung99** [comment]
### 해결
코드 수정 완료. 추후에 front-main-v3로 push 예정
