### ISSUE TITLE
⚡️BACK : 북마크 조회 / 평가된 레시피 조회 / 추천 레시피 조회 API 키이름 변경 요청

### ISSUE THREAD

**Issue by mxxseonkim** [xiu0327/2023-refrigerator-recipe#76]
<img width="568" alt="image" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/71897498/7a661f98-6187-4d61-bdd4-a90981383697">

### 요청 내용
- 북마크 조회 API ( ```/api/my-bookmark/list``` ) 의 응답 데이터 키이름 2개 변경 요청
    - ```recipeId``` → ```recipeID```
    - ```recipeImage``` → ```image```
- 레시피 조회 데이터와 맞추기 위함

**Comment by xiu0327** [comment]
<img width="668" alt="스크린샷 2023-05-23 오후 2 52 31" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/2fa4d2db-5571-48d5-9619-89664ad7018f">

<br>

- 2023.05.23 오후 2시 52분 Update 완료

- 변경사항 API 서버에 배포 완료

**Comment by mxxseonkim** [comment]
## 요청 내용

<img width="574" alt="image" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/71897498/e8bbbdd2-337c-4042-b87f-40067cbc68d5">

- 평가된 레시피 조회 API ( /api/my-score/list ) 의 응답 데이터 키이름 2개 변경 요청
recipeId → recipeID
recipeImage → image
추가로 scoreId → scoreID 로 요청
- 레시피 조회 데이터와 맞추기 위함
- 북마크 조회 API랑 같은 요청 사항입니다.

**Comment by xiu0327** [comment]
### 요청 결과
<img width="666" alt="스크린샷 2023-05-25 오후 2 40 45" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/0891e33a-30d8-4579-a281-e95fd3c3b1ca">

- 2023.05.25 오후 2시 48분 API Update 완료

**Comment by mxxseonkim** [comment]
## 요청 내용

<img width="562" alt="image" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/71897498/f30a30f4-a93d-4981-9165-ba962dbaabe1">

- 추천 레시피 조회 API ( /api/recipe/recommend ) 의 응답 데이터 키이름 변경 요청
recipeId → recipeID
recipeImage → image

## 질문

1. RecipeScore는 scoreAvg랑 같은 값인가요?
맞다면 RecipeScore → scoreAvg 변경 부탁 드립니다

2. 이 데이터에는 조회수 (views) 는 없는건가요?

3. match의 최고값은 무엇인가요?
( 일치값 / 최고값 ) 으로 일치율을 시각화해서 필요합니다.

**Comment by xiu0327** [comment]
### 요청 결과

<img width="657" alt="스크린샷 2023-05-28 오전 12 44 58" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/69abcf11-32e9-4826-bc95-20d22aff1328">

<br>
<br>

- match 값 계산 오류 수정
- 최고 값은 백분율이기 때문에 항상 100.0 이하 입니다 ~ 
- 2023.05.28 오전 12시 47분 Update


### 또 .. 다른 버그
- 일치율이 내림차순으로 정렬되어 안 나타나는 문제를 차차 고쳐보겠음 ..

**Comment by xiu0327** [comment]
### 요청 결과

<img width="664" alt="스크린샷 2023-05-28 오후 8 14 50" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/1cf0ca12-6f45-4872-9b5b-cb6ce5189870">

- 일치율을 내림차순으로 정렬
- 2023.05.28 오후 8시 15분 Update
