### ISSUE TITLE
✨FRONT : favicon 오류

### ISSUE THREAD

**Issue by j-kyung99** [xiu0327/2023-refrigerator-recipe#84]
### 이슈 내용
- 아래와 같은 favicon 오류 발생
<img width="334" alt="image" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/86589951/a4e66d66-94d9-4a5d-9701-e7ec0555d7e5">

### 해결
- front/public에 favicon 생성 후 pages/_document.tsx의 Header 부분에 <link rel="icon" href="/favicon.ico" /> 추가
<img width="122" alt="image" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/86589951/ad963142-2dd9-4cfe-96e7-64da623560c1">
- 아이콘 생성 및 오류 해결 완료!

**Comment by mxxseonkim** [comment]
<img width="678" alt="image" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/71897498/0cc6ddd8-485a-46d3-92fc-8d72edb353f9">

<img width="239" alt="image" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/71897498/f843e5ff-f4cb-41f5-b25e-79227bf4403b">

### 이슈 내용
- favicon.png, pages/_document.tsx 변경 내용 적용한 상태
- favicon 401 오류 계속 뜸
- 브라우저 탭에도 아이콘 적용 안됐음

**Comment by j-kyung99** [comment]
favicon.png -> favicon.ico로 변경함. 다시 pull 받아주세요! 실수 ... 죄송합니다 ... !
