### ISSUE TITLE
⚡️BACK : 추천 검색어 중복 제거 요청

### ISSUE THREAD

**Issue by mxxseonkim** [xiu0327/2023-refrigerator-recipe#90]
## 요청 내용
- 추천 검색어 중복 제거 요청
- 그리고 오류가 난 것 같음
지금 내 계정의 냉장고에는 사과가 2개 있는데 추천 검색어에는 3개가 뜸
사용자 냉장고에 사골은 아예 등록되어 있지 않음

(참고로 어제 낮에는 잘 돌아갔음)

<img width="265" alt="image" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/71897498/34f203ef-5e78-41f3-b8bb-c5d8da5b05ef">

**Comment by xiu0327** [comment]
<img width="1115" alt="스크린샷 2023-05-26 오후 1 43 40" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/3f609050-b818-4076-a9fe-63119d4e0070">

DB 내용 확인해보니까 사골 2개, 사과 4개가 있더라 ..~
테스트 데이터는 랜덤으로 생성되기 때문에 중복된 데이터가 들어갈 수 있음...~
일단 식재료 등록할 때 중복 처리 로직이 필요할 것 같음 이부분은 식빵한테 너가 따로 요청해주길 바라 ~
추천 검색어 쪽에서도 중복 없이 5개의 결과가 나올 수 있게 처리해두도록 할게 ~

**Comment by xiu0327** [comment]
### 수정 결과

<img width="332" alt="스크린샷 2023-05-28 오후 8 24 54" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/a4b2ad28-1962-48b6-91dd-fbe10b24b3dd">

- deleted 상태인 식재료를 제외하고 추천 검색어 추출
- 식재료 이름을 기준으로 중복 제거
- 2023.05.28 오후 8시 25분 API 서버 Update
