### ISSUE TITLE
✨ FRONT : 사용자가 식재료를 등록하지 않았을 때, 추천 레시피 에러

### ISSUE THREAD

**Issue by xiu0327** [xiu0327/2023-refrigerator-recipe#98]
### 이슈 상황

<img width="1473" alt="스크린샷 2023-06-05 오후 4 28 59" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/78461009/d62936d0-7f86-4087-ac03-531a29fe4cd2">

- 사용자가 식재료를 등록하지 않고 추천 레시피를 눌렀을 때 위와 같은 에러가 발생
- Back-end에서 보낸 에러를 팝업창 혹은 안내문으로 변경할 필요

**Comment by mxxseonkim** [comment]
<img width="358" alt="image" src="https://github.com/xiu0327/2023-refrigerator-recipe/assets/71897498/7a1a35e6-67ca-46a6-849e-5c4d04c03958">
오류 처리하고 오류에 대해 알리는 UI 구현
